services:
  django-soft:
    container_name: dchat
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - psql
    restart: always
    entrypoint: bash ./launch.sh
    volumes:
      - .:/usr/src/app/
    env_file: .env
    expose:
      - 8000
    ports:
      - "8081:8000"
    networks:
      - back
      - front

  psql:
    container_name: pchat
    image: postgres
    restart: unless-stopped
    shm_size: 256mb
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${PSQL_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_MASTER_USER}
      DB_USER: ${PSQL_USER}
      DB: ${PSQL_DATABASE}
      DB_PASS: ${PSQL_PASS}
    volumes:
      - psql:/var/lib/postgresql/data
      - ./postgres/init.sh:/scripts/init.sh
    networks:
      - back

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - back
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  psql:
  redis_data:

networks:
  front:
    ipam:
      config:
        - subnet: 172.32.0.0/16
  back:
    ipam:
      config:
        - subnet: 172.31.0.0/16