# Generated by Django 5.0.6 on 2024-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid_redacted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
