# Generated by Django 5.0.6 on 2024-09-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_uuid_redacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uuid_redacted',
        ),
    ]
