#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';
	CREATE DATABASE ${DB};
	GRANT ALL PRIVILEGES ON DATABASE ${DB} TO ${DB_USER};
    GRANT ALL ON SCHEMA public TO ${DB_USER};
    ALTER SCHEMA public OWNER TO ${DB_USER};
EOSQL