name: Commit patrol
on:
  pull_request:
    branches: ["main"]

env:
  GITHUBACTION: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Install pre-commit hooks
        run: pre-commit install --install-hook

      - name: Run pre-commit on changed files
        run: |
          git diff --name-only origin/${{ github.base_ref }} | xargs pre-commit run --files
